# Generated by Django 4.2.23 on 2025-08-07 12:05

import attendance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='image',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='event_files/', validators=[attendance_app.models.validate_file_type]),
        ),
    ]
