# Generated by Django 4.2.23 on 2025-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
                ('english', models.IntegerField(blank=True, null=True)),
                ('malayalam', models.IntegerField(blank=True, null=True)),
                ('ss', models.IntegerField(blank=True, null=True)),
                ('ed', models.IntegerField(blank=True, null=True)),
                ('workshop', models.IntegerField(blank=True, null=True)),
                ('eye', models.IntegerField(blank=True, null=True)),
                ('ge', models.IntegerField(blank=True, null=True)),
                ('tradeTheory', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone_num',
            field=models.CharField(max_length=10),
        ),
    ]
