# Generated by Django 4.2.23 on 2025-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_studentmark_alter_admission_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
