# Generated by Django 4.2.23 on 2025-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_alter_admission_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
