# Generated by Django 4.2.23 on 2025-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_studentmark_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='exam',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Annual Exam', 'Annual Exam')], default='First Term', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('division', 'roll_no', 'year', 'exam')},
        ),
    ]
