# Generated by Django 4.2.23 on 2025-08-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_studentmark_exam_alter_studentmark_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('division', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
            ],
        ),
    ]
